import { NetworkDevice, NetworkLink, TopologyData } from '../types/network';

export interface PresetScenario {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category: 'Dasar' | 'Fiber Optic FTTH' | 'Enterprise Routing' | 'IoT Otomasi' | 'Traffic Load' | 'Tantangan';
  icon: string;
  devices: NetworkDevice[];
  links: NetworkLink[];
}

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'soho_basic',
    name: 'Jaringan Kantor SOHO & VLAN',
    tagline: 'Router + Switch Managed L2/L3 + VLAN Staff & Tamu',
    description: 'Topologi kantor modern dengan Router Gateway, Switch Managed dengan pemisahan VLAN 10 (Staff) dan VLAN 20 (Tamu), Server berkas, PC, dan Wi-Fi.',
    category: 'Dasar',
    icon: 'Building2',
    devices: [
      {
        id: 'dev_cloud_1',
        name: 'ISP_Cloud',
        type: 'cloud_internet',
        category: 'routing',
        x: 480,
        y: 60,
        status: 'online',
        ports: [
          {
            id: 'p_cloud_1',
            name: 'WAN0',
            type: 'ethernet_ge',
            isUp: true,
            mac: '00:11:22:33:44:00',
            ipAssignment: 'static',
            ipAddress: '8.8.8.8',
            subnetMask: '255.255.255.0',
            speedMbps: 10000,
          },
        ],
      },
      {
        id: 'dev_router_1',
        name: 'Router_Gateway',
        type: 'router',
        category: 'routing',
        x: 480,
        y: 180,
        status: 'online',
        ports: [
          {
            id: 'p_r1_wan',
            name: 'GigabitEthernet0/0',
            type: 'ethernet_ge',
            isUp: true,
            mac: '00:D0:D3:44:00:01',
            ipAssignment: 'static',
            ipAddress: '8.8.8.2',
            subnetMask: '255.255.255.0',
            defaultGateway: '8.8.8.8',
            speedMbps: 1000,
          },
          {
            id: 'p_r1_lan',
            name: 'GigabitEthernet0/1',
            type: 'ethernet_ge',
            isUp: true,
            mac: '00:D0:D3:44:00:02',
            ipAssignment: 'static',
            ipAddress: '192.168.1.1',
            subnetMask: '255.255.255.0',
            speedMbps: 1000,
          },
        ],
        dhcpServer: {
          enabled: true,
          interfaceName: 'GigabitEthernet0/1',
          network: '192.168.1.0',
          netmask: '255.255.255.0',
          rangeStart: '192.168.1.10',
          rangeEnd: '192.168.1.100',
          gateway: '192.168.1.1',
          dns: '8.8.8.8',
          leaseTimeHours: 24,
        },
      },
      {
        id: 'dev_switch_1',
        name: 'Switch_Core_L2',
        type: 'switch',
        category: 'switching',
        x: 480,
        y: 310,
        status: 'online',
        ports: [
          { id: 'p_sw1_gi1', name: 'Gi0/1 (Uplink)', type: 'ethernet_ge', isUp: true, mac: '00:E0:F7:44:00:09', ipAssignment: 'none', speedMbps: 1000, vlanMode: 'trunk', trunkAllowedVlans: [1, 10, 20] },
          { id: 'p_sw1_fa1', name: 'Fa0/1 (VLAN 10)', type: 'ethernet_fe', isUp: true, mac: '00:E0:F7:44:00:01', ipAssignment: 'none', speedMbps: 100, vlanMode: 'access', vlanId: 10 },
          { id: 'p_sw1_fa2', name: 'Fa0/2 (VLAN 10)', type: 'ethernet_fe', isUp: true, mac: '00:E0:F7:44:00:02', ipAssignment: 'none', speedMbps: 100, vlanMode: 'access', vlanId: 10 },
          { id: 'p_sw1_fa3', name: 'Fa0/3 (VLAN 20)', type: 'ethernet_fe', isUp: true, mac: '00:E0:F7:44:00:03', ipAssignment: 'none', speedMbps: 100, vlanMode: 'access', vlanId: 20 },
          { id: 'p_sw1_fa4', name: 'Fa0/4', type: 'ethernet_fe', isUp: true, mac: '00:E0:F7:44:00:04', ipAssignment: 'none', speedMbps: 100, vlanMode: 'access', vlanId: 10 },
        ],
      },
      {
        id: 'dev_pc_1',
        name: 'PC_Keuangan',
        type: 'pc',
        category: 'end_device',
        x: 230,
        y: 440,
        status: 'online',
        ports: [
          {
            id: 'p_pc1_ge',
            name: 'FastEthernet0',
            type: 'ethernet_fe',
            isUp: true,
            mac: '00:01:C7:11:00:01',
            ipAssignment: 'static',
            ipAddress: '192.168.1.10',
            subnetMask: '255.255.255.0',
            defaultGateway: '192.168.1.1',
            speedMbps: 100,
            vlanId: 10,
          },
        ],
      },
      {
        id: 'dev_pc_2',
        name: 'PC_Direksi',
        type: 'pc',
        category: 'end_device',
        x: 400,
        y: 440,
        status: 'online',
        ports: [
          {
            id: 'p_pc2_ge',
            name: 'FastEthernet0',
            type: 'ethernet_fe',
            isUp: true,
            mac: '00:01:C7:11:00:02',
            ipAssignment: 'static',
            ipAddress: '192.168.1.11',
            subnetMask: '255.255.255.0',
            defaultGateway: '192.168.1.1',
            speedMbps: 100,
            vlanId: 10,
          },
        ],
      },
      {
        id: 'dev_laptop_1',
        name: 'Laptop_Tamu',
        type: 'laptop',
        category: 'end_device',
        x: 580,
        y: 440,
        status: 'online',
        ports: [
          {
            id: 'p_lap1_fe',
            name: 'FastEthernet0',
            type: 'ethernet_fe',
            isUp: true,
            mac: '00:02:B3:22:00:01',
            ipAssignment: 'static',
            ipAddress: '192.168.1.25',
            subnetMask: '255.255.255.0',
            defaultGateway: '192.168.1.1',
            speedMbps: 100,
            vlanId: 20,
          },
        ],
      },
      {
        id: 'dev_printer_1',
        name: 'Printer_Kantor',
        type: 'printer',
        category: 'end_device',
        x: 740,
        y: 440,
        status: 'online',
        ports: [
          {
            id: 'p_print_fe',
            name: 'FastEthernet0',
            type: 'ethernet_fe',
            isUp: true,
            mac: '00:03:D2:33:00:01',
            ipAssignment: 'static',
            ipAddress: '192.168.1.50',
            subnetMask: '255.255.255.0',
            defaultGateway: '192.168.1.1',
            speedMbps: 100,
            vlanId: 10,
          },
        ],
      },
    ],
    links: [
      { id: 'link_c_r', fromDeviceId: 'dev_cloud_1', fromPortId: 'p_cloud_1', toDeviceId: 'dev_router_1', toPortId: 'p_r1_wan', cableType: 'ethernet_straight', lengthMeters: 5, status: 'active' },
      { id: 'link_r_sw', fromDeviceId: 'dev_router_1', fromPortId: 'p_r1_lan', toDeviceId: 'dev_switch_1', toPortId: 'p_sw1_gi1', cableType: 'ethernet_straight', lengthMeters: 10, status: 'active' },
      { id: 'link_sw_pc1', fromDeviceId: 'dev_switch_1', fromPortId: 'p_sw1_fa1', toDeviceId: 'dev_pc_1', toPortId: 'p_pc1_ge', cableType: 'ethernet_straight', lengthMeters: 15, status: 'active' },
      { id: 'link_sw_pc2', fromDeviceId: 'dev_switch_1', fromPortId: 'p_sw1_fa2', toDeviceId: 'dev_pc_2', toPortId: 'p_pc2_ge', cableType: 'ethernet_straight', lengthMeters: 12, status: 'active' },
      { id: 'link_sw_lap', fromDeviceId: 'dev_switch_1', fromPortId: 'p_sw1_fa3', toDeviceId: 'dev_laptop_1', toPortId: 'p_lap1_fe', cableType: 'ethernet_straight', lengthMeters: 20, status: 'active' },
      { id: 'link_sw_print', fromDeviceId: 'dev_switch_1', fromPortId: 'p_sw1_fa4', toDeviceId: 'dev_printer_1', toPortId: 'p_print_fe', cableType: 'ethernet_straight', lengthMeters: 18, status: 'active' },
    ],
  },
  {
    id: 'ftth_gpon_full',
    name: 'Topologi FTTH GPON Lengkap (ODC, ODP, Splitter)',
    tagline: 'OLT SFP -> Feeder -> ODC 1:4 -> ODP 1:8 -> Dropcore -> ONT',
    description: 'Hierarki fisik Fiber-to-the-Home standar industri: Central Office OLT (SFP Class B+), Kabel Feeder Fiber, ODC dengan Primary Splitter 1:4, Kabel Distribusi, ODP dengan Secondary Splitter 1:8, Kabel Dropcore ke ONT Pelanggan dengan visualisasi redaman optik (Rx Power ~ -21.4 dBm).',
    category: 'Fiber Optic FTTH',
    icon: 'Radio',
    devices: [
      {
        id: 'dev_olt_co',
        name: 'OLT_Central_Office',
        type: 'olt',
        category: 'optical',
        x: 480,
        y: 60,
        status: 'online',
        ports: [
          { id: 'p_olt_pon1', name: 'PON0/1 (SFP B+)', type: 'sfp_pon', isUp: true, speedMbps: 2500 },
          { id: 'p_olt_ge1', name: 'GE0/1 Uplink', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '10.10.10.1', subnetMask: '255.255.255.0', speedMbps: 1000 },
        ],
        opticalConfig: {
          sfpModuleType: 'class_b_plus',
          txPowerDbm: +3.0,
          rxSensitivityDbm: -28.0,
        },
      },
      {
        id: 'dev_odc_cluster',
        name: 'ODC_Cluster_Utama',
        type: 'odc',
        category: 'optical',
        x: 480,
        y: 180,
        status: 'online',
        ports: [
          { id: 'p_odc_in', name: 'Feeder IN', type: 'optical_sc', isUp: true },
          { id: 'p_odc_out1', name: 'Dist-1 (Split 1:4)', type: 'optical_sc', isUp: true },
          { id: 'p_odc_out2', name: 'Dist-2 (Split 1:4)', type: 'optical_sc', isUp: true },
        ],
        opticalConfig: {
          splitRatio: '1:4',
          insertionLossDb: 7.2,
          connectorType: 'SC/APC',
        },
      },
      {
        id: 'dev_odp_blok_a',
        name: 'ODP_Tiang_Blok_A',
        type: 'odp',
        category: 'optical',
        x: 320,
        y: 310,
        status: 'online',
        ports: [
          { id: 'p_odp_in', name: 'Dist IN', type: 'optical_sc', isUp: true },
          { id: 'p_odp_d1', name: 'Drop Port 1', type: 'optical_sc', isUp: true },
          { id: 'p_odp_d2', name: 'Drop Port 2', type: 'optical_sc', isUp: true },
        ],
        opticalConfig: {
          splitRatio: '1:8',
          insertionLossDb: 10.5,
          connectorType: 'SC/APC',
        },
      },
      {
        id: 'dev_odp_blok_b',
        name: 'ODP_Tiang_Blok_B',
        type: 'odp',
        category: 'optical',
        x: 640,
        y: 310,
        status: 'online',
        ports: [
          { id: 'p_odpb_in', name: 'Dist IN', type: 'optical_sc', isUp: true },
          { id: 'p_odpb_d1', name: 'Drop Port 1', type: 'optical_sc', isUp: true },
        ],
        opticalConfig: {
          splitRatio: '1:8',
          insertionLossDb: 10.5,
          connectorType: 'SC/APC',
        },
      },
      {
        id: 'dev_ont_rumah_1',
        name: 'ONT_Rumah_A1',
        type: 'ont',
        category: 'optical',
        x: 230,
        y: 440,
        status: 'online',
        ports: [
          { id: 'p_ont1_pon', name: 'PON (SC/APC)', type: 'optical_sc', isUp: true },
          { id: 'p_ont1_lan1', name: 'LAN1 (GE)', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '192.168.18.1', subnetMask: '255.255.255.0', speedMbps: 1000 },
        ],
        opticalConfig: {
          rxSensitivityDbm: -27.0,
          connectorType: 'SC/APC',
        },
      },
      {
        id: 'dev_ont_rumah_2',
        name: 'ONT_Rumah_A2',
        type: 'ont',
        category: 'optical',
        x: 410,
        y: 440,
        status: 'online',
        ports: [
          { id: 'p_ont2_pon', name: 'PON (SC/APC)', type: 'optical_sc', isUp: true },
          { id: 'p_ont2_lan1', name: 'LAN1 (GE)', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '192.168.18.2', subnetMask: '255.255.255.0', speedMbps: 1000 },
        ],
        opticalConfig: {
          rxSensitivityDbm: -27.0,
          connectorType: 'SC/APC',
        },
      },
      {
        id: 'dev_mesh_wifi',
        name: 'Mesh_WiFi_Home',
        type: 'mesh_wifi',
        category: 'wireless',
        x: 230,
        y: 560,
        status: 'online',
        ports: [
          { id: 'p_mesh_wan', name: 'WAN (GE)', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '192.168.18.10', subnetMask: '255.255.255.0', defaultGateway: '192.168.18.1', speedMbps: 1000 },
          { id: 'p_mesh_wlan', name: 'Wi-Fi 6', type: 'wireless', isUp: true },
        ],
      },
    ],
    links: [
      { id: 'l_olt_odc', fromDeviceId: 'dev_olt_co', fromPortId: 'p_olt_pon1', toDeviceId: 'dev_odc_cluster', toPortId: 'p_odc_in', cableType: 'feeder_fiber', lengthMeters: 2500, status: 'active' },
      { id: 'l_odc_odpa', fromDeviceId: 'dev_odc_cluster', fromPortId: 'p_odc_out1', toDeviceId: 'dev_odp_blok_a', toPortId: 'p_odp_in', cableType: 'dist_fiber', lengthMeters: 800, status: 'active' },
      { id: 'l_odc_odpb', fromDeviceId: 'dev_odc_cluster', fromPortId: 'p_odc_out2', toDeviceId: 'dev_odp_blok_b', toPortId: 'p_odpb_in', cableType: 'dist_fiber', lengthMeters: 1200, status: 'active' },
      { id: 'l_odpa_ont1', fromDeviceId: 'dev_odp_blok_a', fromPortId: 'p_odp_d1', toDeviceId: 'dev_ont_rumah_1', toPortId: 'p_ont1_pon', cableType: 'dropcore', lengthMeters: 150, status: 'active' },
      { id: 'l_odpa_ont2', fromDeviceId: 'dev_odp_blok_a', fromPortId: 'p_odp_d2', toDeviceId: 'dev_ont_rumah_2', toPortId: 'p_ont2_pon', cableType: 'dropcore', lengthMeters: 200, status: 'active' },
      { id: 'l_ont1_mesh', fromDeviceId: 'dev_ont_rumah_1', fromPortId: 'p_ont1_lan1', toDeviceId: 'dev_mesh_wifi', toPortId: 'p_mesh_wan', cableType: 'ethernet_straight', lengthMeters: 5, status: 'active' },
    ],
  },
  {
    id: 'enterprise_ospf_bgp',
    name: 'Enterprise Multi-Router (OSPF & BGP Peering)',
    tagline: 'OSPF Area 0 Backbone + eBGP AS 65001 ke ISP AS 65000',
    description: 'Simulasi protokol routing tingkat lanjut sesuai standar Cisco/MikroTik. Router Kantor Pusat dan Cabang saling bertukar tabel rute via OSPF Area 0, dan peering eBGP ke ISP Cloud.',
    category: 'Enterprise Routing',
    icon: 'Share2',
    devices: [
      {
        id: 'dev_isp_core',
        name: 'ISP_Border_AS65000',
        type: 'cloud_internet',
        category: 'routing',
        x: 480,
        y: 60,
        status: 'online',
        ports: [
          { id: 'p_isp_bgp1', name: 'Gi0/0', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '203.0.113.1', subnetMask: '255.255.255.252', speedMbps: 10000 },
        ],
        bgpConfig: {
          enabled: true,
          asNumber: 65000,
          routerId: '203.0.113.1',
          neighbors: [{ neighborIp: '203.0.113.2', remoteAs: 65001, status: 'Established' }],
          advertisedNetworks: ['0.0.0.0/0', '8.8.8.0/24'],
        },
      },
      {
        id: 'dev_router_hq',
        name: 'Router_HQ_Core',
        type: 'router',
        category: 'routing',
        x: 340,
        y: 200,
        status: 'online',
        ports: [
          { id: 'p_rhq_wan', name: 'Gi0/0 (WAN eBGP)', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '203.0.113.2', subnetMask: '255.255.255.252', defaultGateway: '203.0.113.1', speedMbps: 1000 },
          { id: 'p_rhq_inter', name: 'Gi0/1 (OSPF Area 0)', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '10.0.0.1', subnetMask: '255.255.255.252', speedMbps: 1000 },
          { id: 'p_rhq_lan', name: 'Gi0/2 (LAN HQ)', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '172.16.10.1', subnetMask: '255.255.255.0', speedMbps: 1000 },
        ],
        ospfConfig: {
          enabled: true,
          processId: 1,
          routerId: '1.1.1.1',
          areaId: 0,
          cost: 10,
          neighbors: ['2.2.2.2'],
        },
        bgpConfig: {
          enabled: true,
          asNumber: 65001,
          routerId: '1.1.1.1',
          neighbors: [{ neighborIp: '203.0.113.1', remoteAs: 65000, status: 'Established' }],
          advertisedNetworks: ['172.16.10.0/24', '172.16.20.0/24'],
        },
      },
      {
        id: 'dev_router_branch',
        name: 'Router_Cabang_Core',
        type: 'mikrotik',
        category: 'routing',
        x: 620,
        y: 200,
        status: 'online',
        ports: [
          { id: 'p_rbr_inter', name: 'ether1 (OSPF)', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '10.0.0.2', subnetMask: '255.255.255.252', speedMbps: 1000 },
          { id: 'p_rbr_lan', name: 'ether2 (LAN Cabang)', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '172.16.20.1', subnetMask: '255.255.255.0', speedMbps: 1000 },
        ],
        ospfConfig: {
          enabled: true,
          processId: 1,
          routerId: '2.2.2.2',
          areaId: 0,
          cost: 10,
          neighbors: ['1.1.1.1'],
        },
      },
      {
        id: 'dev_server_hq',
        name: 'Database_HQ',
        type: 'server',
        category: 'end_device',
        x: 340,
        y: 360,
        status: 'online',
        ports: [
          { id: 'p_srv_ge', name: 'eth0', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '172.16.10.100', subnetMask: '255.255.255.0', defaultGateway: '172.16.10.1', speedMbps: 1000 },
        ],
      },
      {
        id: 'dev_pc_branch',
        name: 'PC_Client_Cabang',
        type: 'pc',
        category: 'end_device',
        x: 620,
        y: 360,
        status: 'online',
        ports: [
          { id: 'p_pcbr_ge', name: 'FastEthernet0', type: 'ethernet_fe', isUp: true, ipAssignment: 'static', ipAddress: '172.16.20.50', subnetMask: '255.255.255.0', defaultGateway: '172.16.20.1', speedMbps: 100 },
        ],
      },
    ],
    links: [
      { id: 'l_isp_hq', fromDeviceId: 'dev_isp_core', fromPortId: 'p_isp_bgp1', toDeviceId: 'dev_router_hq', toPortId: 'p_rhq_wan', cableType: 'ethernet_straight', lengthMeters: 50, status: 'active' },
      { id: 'l_hq_branch', fromDeviceId: 'dev_router_hq', fromPortId: 'p_rhq_inter', toDeviceId: 'dev_router_branch', toPortId: 'p_rbr_inter', cableType: 'ethernet_straight', lengthMeters: 200, status: 'active' },
      { id: 'l_hq_srv', fromDeviceId: 'dev_router_hq', fromPortId: 'p_rhq_lan', toDeviceId: 'dev_server_hq', toPortId: 'p_srv_ge', cableType: 'ethernet_straight', lengthMeters: 10, status: 'active' },
      { id: 'l_br_pc', fromDeviceId: 'dev_router_branch', fromPortId: 'p_rbr_lan', toDeviceId: 'dev_pc_branch', toPortId: 'p_pcbr_ge', cableType: 'ethernet_straight', lengthMeters: 15, status: 'active' },
    ],
  },
  {
    id: 'iot_smart_office',
    name: 'Smart Building & IoT Otomasi',
    tagline: 'Sensor Suhu + Smart Plug (AC) + Smart Cam + IoT Hub',
    description: 'Integrasi perangkat IoT cerdas dengan jaringan IP konvensional. Sensor Suhu server memicu Smart Plug pendingin udara secara otomatis ketika suhu > 30°C, terhubung ke Dashboard PC Pengawas.',
    category: 'IoT Otomasi',
    icon: 'Cpu',
    devices: [
      {
        id: 'dev_iot_gateway',
        name: 'Gateway_Smart_Office',
        type: 'router',
        category: 'routing',
        x: 480,
        y: 80,
        status: 'online',
        ports: [
          { id: 'p_gw_lan', name: 'Gi0/1', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '192.168.50.1', subnetMask: '255.255.255.0', speedMbps: 1000 },
        ],
      },
      {
        id: 'dev_iot_hub',
        name: 'IoT_Hub_Zigbee_IP',
        type: 'iot_hub',
        category: 'iot',
        x: 480,
        y: 220,
        status: 'online',
        ports: [
          { id: 'p_hub_lan', name: 'ETH0', type: 'ethernet_fe', isUp: true, ipAssignment: 'static', ipAddress: '192.168.50.2', subnetMask: '255.255.255.0', defaultGateway: '192.168.50.1', speedMbps: 100 },
          { id: 'p_hub_wlan', name: 'IoT RF', type: 'wireless', isUp: true },
        ],
      },
      {
        id: 'dev_sensor_suhu',
        name: 'Sensor_Suhu_Ruang_Server',
        type: 'sensor_temp',
        category: 'iot',
        x: 260,
        y: 350,
        status: 'online',
        ports: [
          { id: 'p_stemp_wlan', name: 'WiFi', type: 'wireless', isUp: true, ipAssignment: 'static', ipAddress: '192.168.50.101', subnetMask: '255.255.255.0', defaultGateway: '192.168.50.1' },
        ],
        iotTelemetry: {
          deviceCategory: 'sensor',
          tempCelsius: 34.5,
          humidityPercent: 62,
          telemetryIntervalSec: 5,
          automationRules: [
            {
              id: 'rule_overheat',
              name: 'Nyalakan AC saat Server Panas',
              trigger: 'temp_above',
              threshold: 30,
              targetDeviceId: 'dev_smart_plug_ac',
              action: 'turn_on_plug',
              enabled: true,
            },
          ],
        },
      },
      {
        id: 'dev_smart_plug_ac',
        name: 'Smart_Plug_AC_Cooler',
        type: 'smart_plug',
        category: 'iot',
        x: 480,
        y: 350,
        status: 'online',
        ports: [
          { id: 'p_splug_wlan', name: 'WiFi', type: 'wireless', isUp: true, ipAssignment: 'static', ipAddress: '192.168.50.102', subnetMask: '255.255.255.0', defaultGateway: '192.168.50.1' },
        ],
        iotTelemetry: {
          deviceCategory: 'actuator',
          plugState: 'ON',
          powerWatt: 850,
        },
      },
      {
        id: 'dev_smart_cam_1',
        name: 'Smart_Cam_ServerRoom',
        type: 'smart_cam',
        category: 'iot',
        x: 700,
        y: 350,
        status: 'online',
        ports: [
          { id: 'p_scam_fe', name: 'LAN/PoE', type: 'ethernet_fe', isUp: true, ipAssignment: 'static', ipAddress: '192.168.50.103', subnetMask: '255.255.255.0', defaultGateway: '192.168.50.1', speedMbps: 100 },
        ],
        iotTelemetry: {
          deviceCategory: 'camera',
          motionDetected: false,
          batteryPercent: 100,
        },
      },
      {
        id: 'dev_pc_iot_mon',
        name: 'PC_Monitoring_IoT',
        type: 'pc',
        category: 'end_device',
        x: 480,
        y: 490,
        status: 'online',
        ports: [
          { id: 'p_pc_mon_ge', name: 'GigabitEthernet0', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '192.168.50.10', subnetMask: '255.255.255.0', defaultGateway: '192.168.50.1', speedMbps: 1000 },
        ],
      },
    ],
    links: [
      { id: 'l_gw_hub', fromDeviceId: 'dev_iot_gateway', fromPortId: 'p_gw_lan', toDeviceId: 'dev_iot_hub', toPortId: 'p_hub_lan', cableType: 'ethernet_straight', lengthMeters: 5, status: 'active' },
      { id: 'l_hub_temp', fromDeviceId: 'dev_iot_hub', fromPortId: 'p_hub_wlan', toDeviceId: 'dev_sensor_suhu', toPortId: 'p_stemp_wlan', cableType: 'wireless_link', lengthMeters: 8, status: 'active' },
      { id: 'l_hub_plug', fromDeviceId: 'dev_iot_hub', fromPortId: 'p_hub_wlan', toDeviceId: 'dev_smart_plug_ac', toPortId: 'p_splug_wlan', cableType: 'wireless_link', lengthMeters: 10, status: 'active' },
      { id: 'l_hub_cam', fromDeviceId: 'dev_iot_hub', fromPortId: 'p_hub_wlan', toDeviceId: 'dev_smart_cam_1', toPortId: 'p_scam_fe', cableType: 'ethernet_straight', lengthMeters: 15, status: 'active' },
      { id: 'l_hub_pcmon', fromDeviceId: 'dev_iot_hub', fromPortId: 'p_hub_lan', toDeviceId: 'dev_pc_iot_mon', toPortId: 'p_pc_mon_ge', cableType: 'ethernet_straight', lengthMeters: 20, status: 'active' },
    ],
  },
  {
    id: 'traffic_congestion_test',
    name: 'Simulasi Beban Traffic & Bottleneck Link',
    tagline: 'Traffic Generator 90 Mbps pada Link FE 100 Mbps',
    description: 'Skenario demonstrasi beban traffic tinggi. PC Pengirim membanjiri link Fast Ethernet (100 Mbps) menuju Server. Saat generator aktif, visual link berubah merah berkedip, latency melonjak dari 2ms ke 110ms, dan packet loss terjadi.',
    category: 'Traffic Load',
    icon: 'Activity',
    devices: [
      {
        id: 'dev_pc_sender',
        name: 'PC_Traffic_Generator',
        type: 'pc',
        category: 'end_device',
        x: 240,
        y: 260,
        status: 'online',
        ports: [
          { id: 'p_pcs_ge', name: 'GigabitEthernet0', type: 'ethernet_ge', isUp: true, ipAssignment: 'static', ipAddress: '10.10.100.5', subnetMask: '255.255.255.0', defaultGateway: '10.10.100.1', speedMbps: 1000 },
        ],
      },
      {
        id: 'dev_sw_bottleneck',
        name: 'Switch_Bottleneck_FE',
        type: 'switch_hub',
        category: 'switching',
        x: 480,
        y: 260,
        status: 'online',
        ports: [
          { id: 'p_swb_fa1', name: 'Fa0/1 (100M)', type: 'ethernet_fe', isUp: true, ipAssignment: 'none', speedMbps: 100 },
          { id: 'p_swb_fa2', name: 'Fa0/2 (100M Bottleneck)', type: 'ethernet_fe', isUp: true, ipAssignment: 'none', speedMbps: 100 },
        ],
      },
      {
        id: 'dev_server_target',
        name: 'Server_Pusat_Data',
        type: 'server',
        category: 'end_device',
        x: 720,
        y: 260,
        status: 'online',
        ports: [
          { id: 'p_srv_target', name: 'eth0 (100M)', type: 'ethernet_fe', isUp: true, ipAssignment: 'static', ipAddress: '10.10.100.100', subnetMask: '255.255.255.0', speedMbps: 100 },
        ],
      },
    ],
    links: [
      { id: 'link_pcs_swb', fromDeviceId: 'dev_pc_sender', fromPortId: 'p_pcs_ge', toDeviceId: 'dev_sw_bottleneck', toPortId: 'p_swb_fa1', cableType: 'ethernet_straight', lengthMeters: 10, status: 'active' },
      { id: 'link_bottleneck_critical', fromDeviceId: 'dev_sw_bottleneck', fromPortId: 'p_swb_fa2', toDeviceId: 'dev_server_target', toPortId: 'p_srv_target', cableType: 'ethernet_straight', lengthMeters: 50, status: 'active' },
    ],
  },
  {
    id: 'troubleshooting_challenge',
    name: 'Tantangan Pemecahan Masalah (Troubleshoot)',
    tagline: 'Topologi dengan 4 Kesalahan Tersembunyi!',
    description: 'Skenario khusus yang berisi 4 masalah nyata jaringan (IP Konflik, Port DOWN, Gateway hilang, dan Redaman Fiber terlalu tinggi). Uji keterampilan teknisi Anda untuk mendiagnosa dan memperbaikinya!',
    category: 'Tantangan',
    icon: 'AlertTriangle',
    devices: [
      {
        id: 'dev_tb_router',
        name: 'Router_Utama',
        type: 'router',
        category: 'routing',
        x: 480,
        y: 100,
        status: 'online',
        ports: [
          {
            id: 'p_tb_r_lan',
            name: 'GigabitEthernet0/1',
            type: 'ethernet_ge',
            isUp: true,
            mac: '00:D0:D3:55:00:01',
            ipAssignment: 'static',
            ipAddress: '192.168.10.1',
            subnetMask: '255.255.255.0',
            speedMbps: 1000,
          },
        ],
      },
      {
        id: 'dev_tb_switch',
        name: 'Switch_Divisi',
        type: 'switch',
        category: 'switching',
        x: 480,
        y: 260,
        status: 'online',
        ports: [
          {
            id: 'p_tb_sw_fa1',
            name: 'Fa0/1',
            type: 'ethernet_fe',
            isUp: true,
            mac: '00:E0:F7:55:00:01',
            ipAssignment: 'none',
            speedMbps: 100,
          },
          {
            id: 'p_tb_sw_fa2',
            name: 'Fa0/2',
            type: 'ethernet_fe',
            isUp: false, // ERROR 1: PORT IS ADMINISTRATIVELY DOWN
            mac: '00:E0:F7:55:00:02',
            ipAssignment: 'none',
            speedMbps: 100,
          },
          {
            id: 'p_tb_sw_fa3',
            name: 'Fa0/3',
            type: 'ethernet_fe',
            isUp: true,
            mac: '00:E0:F7:55:00:03',
            ipAssignment: 'none',
            speedMbps: 100,
          },
          {
            id: 'p_tb_sw_gi1',
            name: 'Gi0/1',
            type: 'ethernet_ge',
            isUp: true,
            mac: '00:E0:F7:55:00:09',
            ipAssignment: 'none',
            speedMbps: 1000,
          },
        ],
      },
      {
        id: 'dev_tb_pc1',
        name: 'PC_Staff_A',
        type: 'pc',
        category: 'end_device',
        x: 250,
        y: 430,
        status: 'online',
        ports: [
          {
            id: 'p_tb_pc1_ge',
            name: 'GigabitEthernet0',
            type: 'ethernet_ge',
            isUp: true,
            mac: '00:1B:44:99:00:01',
            ipAssignment: 'static',
            ipAddress: '192.168.10.50', // ERROR 2: IP CONFLICT WITH PC_Staff_B
            subnetMask: '255.255.255.0',
            defaultGateway: '192.168.10.1',
            speedMbps: 1000,
          },
        ],
      },
      {
        id: 'dev_tb_pc2',
        name: 'PC_Staff_B',
        type: 'pc',
        category: 'end_device',
        x: 480,
        y: 430,
        status: 'online',
        ports: [
          {
            id: 'p_tb_pc2_ge',
            name: 'GigabitEthernet0',
            type: 'ethernet_ge',
            isUp: true,
            mac: '00:1B:44:99:00:02',
            ipAssignment: 'static',
            ipAddress: '192.168.10.50', // ERROR 2: DUPLICATE IP CONFLICT!
            subnetMask: '255.255.255.0',
            defaultGateway: '192.168.10.1',
            speedMbps: 1000,
          },
        ],
      },
      {
        id: 'dev_tb_pc3',
        name: 'PC_Staff_C',
        type: 'pc',
        category: 'end_device',
        x: 710,
        y: 430,
        status: 'online',
        ports: [
          {
            id: 'p_tb_pc3_ge',
            name: 'GigabitEthernet0',
            type: 'ethernet_ge',
            isUp: true,
            mac: '00:1B:44:99:00:03',
            ipAssignment: 'static',
            ipAddress: '192.168.10.75',
            subnetMask: '255.255.255.0',
            defaultGateway: '', // ERROR 3: MISSING DEFAULT GATEWAY!
            speedMbps: 1000,
          },
        ],
      },
    ],
    links: [
      {
        id: 'link_tb_r_sw',
        fromDeviceId: 'dev_tb_router',
        fromPortId: 'p_tb_r_lan',
        toDeviceId: 'dev_tb_switch',
        toPortId: 'p_tb_sw_gi1',
        cableType: 'ethernet_straight',
        lengthMeters: 10,
        status: 'active',
      },
      {
        id: 'link_tb_sw_pc1',
        fromDeviceId: 'dev_tb_switch',
        fromPortId: 'p_tb_sw_fa1',
        toDeviceId: 'dev_tb_pc1',
        toPortId: 'p_tb_pc1_ge',
        cableType: 'ethernet_straight',
        lengthMeters: 15,
        status: 'active',
      },
      {
        id: 'link_tb_sw_pc2',
        fromDeviceId: 'dev_tb_switch',
        fromPortId: 'p_tb_sw_fa2', // PLUGGED INTO PORT THAT IS DOWN!
        toDeviceId: 'dev_tb_pc2',
        toPortId: 'p_tb_pc2_ge',
        cableType: 'ethernet_straight',
        lengthMeters: 15,
        status: 'active',
      },
      {
        id: 'link_tb_sw_pc3',
        fromDeviceId: 'dev_tb_switch',
        fromPortId: 'p_tb_sw_fa3',
        toDeviceId: 'dev_tb_pc3',
        toPortId: 'p_tb_pc3_ge',
        cableType: 'ethernet_straight',
        lengthMeters: 20,
        status: 'active',
      },
    ],
  },
];
